### ISSUE TITLE
Setup Redux for our React App

### ISSUE THREAD

**Issue by edwardlach** [PSU-CMPSC-445/web-app#3]
[React Redux Tutorial](https://www.valentinog.com/blog/redux/)

We need to setup redux for state management in our React app.  We could probably get away with just using React's default state control, but that could cause some state management issues down the line when we start switching between the various components in our single page web app.  It will be more work up front, but should prevent lots of potential headache down the line to use a proper state management flow like Redux from the get go.  This will likely take someone a full week to implement.

**Comment by Ramy-Huffman** [comment]
Created simple redux pattern. Uses reducers to manage different states.
